// Interface automatically generated by schemas-to-ts

import { Skill } from "../../../skill/content-types/skill/skill";
import { Skill_Plain } from "../../../skill/content-types/skill/skill";
import { AdminPanelRelationPropertyModification } from "../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification";

export interface SkillType {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Name?: string;
  skills: Skill_Plain[];
}
