// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface SocialLink {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Name: string;
    Link: string;
    Icon: { data: Media };
  };
}
export interface SocialLink_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Name: string;
  Link: string;
  Icon: Media;
}

export interface SocialLink_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Name: string;
  Link: string;
  Icon: number;
}

export interface SocialLink_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Name: string;
  Link: string;
  Icon: AdminPanelRelationPropertyModification<Media>;
}
