// Interface automatically generated by schemas-to-ts

import { Skill } from '../../../skill/content-types/skill/skill';
import { Skill_Plain } from '../../../skill/content-types/skill/skill';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface SkillType {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Name?: string;
    skills: { data: Skill[] };
  };
}
export interface SkillType_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Name?: string;
  skills: Skill_Plain[];
}

export interface SkillType_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Name?: string;
  skills: number[];
}

export interface SkillType_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Name?: string;
  skills: AdminPanelRelationPropertyModification<Skill_Plain>;
}
