// Interface automatically generated by schemas-to-ts

export interface Test {
  Test?: string;
}
export interface Test_Plain {
  Test?: string;
}

export interface Test_NoRelations {
  Test?: string;
}

